/* 	$Id$	 */

# ifndef FOF_STUFF_H
# define FOF_STUFF_H

# ifdef notyet

static constchar *fof_fieldlist[] = {
";",
"comment:  this file contains information relating numeric ids for raw radar",
"data tape fields, to mnemonics for these raw fields, to related mnemonics",
"used in access packages. Source fields occur before derived fields;",
";",
"comment:  argument no.1 is the field mnemonic recognized by CAP that requires",
"          the specified raw field for input;",
";",
"comment:  argument no.2 is the raw field mnemonic;",
";",
"comment:  argument no.3 is the raw field id no. associated with this field",
"          which is found in the upper byte of the parameter descriptor (PD)",
"          for this field.",
"          With the advent of the MHR the second nibble is now being also used",
"          for ids. To make things work with past history the 2 nibbles are",
"          swaped to form the id no. If the second nibble is zero, then the",
"          id no. doesn't change, but if there is a one in the second nibble",
"          the id becomes 16 plus the contents of the first nibble, etc.;",
" ",
";",
"comment:  argument no.4 is a 4 character \"units\" descriptor used in the",
"          RDSS editor and perusal displays;",
";",
"comment:  argument no.5 is a description of this field. The exclamation",
"          point ! is to further identify and distinguish the description",
"          field;",
";",
"comment:  underscores_are_used_because_the_input_algorithm_squeezes_out",
"          all_of_the_blanks. This make the description more readable if",
"          the attribute is printed;",
";",
"comment:  the description field should contain the word PRIMARY if the source",
"          of this field is C-BAND or S-BAND;",
";",
"comment:  the description field should contain the word SECONDARY if the source",
"          of this field is X-BAND;",
";",
"^-----------------------------------------------------------------------------;",
";",
";",
"source:DM,CP,1,~DBM.,!primary_wavelength_received_log_video_(horizontal);",
";",
"source:ZR,CD,2,~ZDDB,!primary_polarization_diversity;",
";",
"source:DL,CN,3,~DBM.,!primary_wavelength_received_log_video_(vertical);",
";",
"source:RT,CT,4,~RTAU,!primary_r(tau)_(horizontal);",
";",
"source:LM,CO,5,~DBM.,!primary_r(0)_(horizontal);",
";",
"source:XM,CX,6,~DBM.,!secondary_wavelength_received_log_video_(horizontal);",
";",
"source:XL,CY,7,~DBM.,!secondary_wavelength_received_log_video_(vertical);",
";",
"source:VR,CV,8,~M/S.,!primary_wavelength_velocity_(horizontal);",
";",
"source:FL,FL,9,~VFLG,!primary_two_variable_velocity_flag_(horizontal);",
";",
"source:VQ,CU,10,~M/S.,!primary_wavelength_velocity_(vertical);",
";",
"source:LW,CR,11,~----,!primary_compressed_r(0)_and_r(tau)_(vertical);",
";",
"source:LX,CQ,12,~----,!primary_compressed_r(0)_and_r(tau)_(horizontal);",
";",
"source:SR,CW,13,~M/S.,!primary_spectral_width_data_(mist86+);",
";",
"source:RS,CM,14,~SNDB,!primary_s/n_for_Lincoln_lab_tapes;",
";",
"source:LL,CL,15,~DBM.,!primary_r(0)_(vertical);",
";",
"source:VJ,CS,247,~M/S.,!Wierd_JAWS_velocity_descriptor!;",
";",
";",
"source:BZ,BZ,16,~CNTS,!primary_dbz_MHR_(horizontal);",
"; comment:this corresponds to a 01 (hex) in the upper byte of the PD;",
";",
"source:BC,BC,17,~CNTS,!primary_uncluttered_dbz_MHR_(horizontal);",
"; comment:this corresponds to a 11 (hex) in the upper byte of the PD;",
";",
"source:BD,BD,18,~CNTS,!primary_polarization_diversity_MHR;",
"; comment:this corresponds to a 21 (hex) in the upper byte of the PD;",
";",
"source:BX,BX,22,~CNTS,!secondary_dbz_MHR_(horizontal);",
"; comment:this corresponds to a 61 (hex) in the upper byte of the PD;",
";",
"source:BL,BL,24,~CNTS,!secondary_linear_depolarization_ratio_MHR_;",
"; comment:this corresponds to a 81 (hex) in the upper byte of the PD;",
";",
"source:BV,BV,32,~CNTS,!primary_unthresholded_velocity_MHR_(horizontal);",
"; comment:this corresponds to a 02 (hex) in the upper byte of the PD;",
";",
"source:BU,BU,33,~CNTS,!primary_unthresholded_velocity_MHR_(horizontal);",
"; comment:this corresponds to a 12 (hex) in the upper byte of the PD;",
";",
"source:BA,BA,34,~CNTS,!primary_de-aliased_velocity_MHR_(horizontal);",
"; comment:this corresponds to a 22 (hex) in the upper byte of the PD;",
";",
"source:BW,BW,48,~CNTS,!primary_spectral_width_data_MHR_(horizontal);",
"; comment:this corresponds to a 03 (hex) in the upper byte of the PD;",
";",
"source:SA,SA,49,~CNTS,!standard_deviation_of_dBz_data_MHR_(horizontal);",
"; comment:this corresponds to a 13 (hex) in the upper byte of the PD;",
";",
"source:SB,SB,50,~CNTS,!standard_deviation_of_SNR_data_MHR_(horizontal);",
"; comment:this corresponds to a 23 (hex) in the upper byte of the PD;",
";",
"source:SC,SC,51,~CNTS,!standard_deviation_of_vel._data_MHR_(horizontal);",
"; comment:this corresponds to a 33 (hex) in the upper byte of the PD;",
";",
"source:SD,SD,52,~CNTS,!mean_of_dBz_data_MHR_(horizontal);",
"; comment:this corresponds to a 43 (hex) in the upper byte of the PD;",
";",
"source:SE,SE,53,~CNTS,!mean_of_SNR_data_MHR_(horizontal);",
"; comment:this corresponds to a 53 (hex) in the upper byte of the PD;",
";",
"source:SF,SF,54,~CNTS,!mean_of_vel._data_MHR_(horizontal);",
"; comment:this corresponds to a 63 (hex) in the upper byte of the PD;",
";",
"source:SG,SG,55,~CNTS,!median_of_dBz_data_MHR_(horizontal);",
"; comment:this corresponds to a 73 (hex) in the upper byte of the PD;",
";",
"source:SH,SH,56,~CNTS,!median_of_SNR_data_MHR_(horizontal);",
"; comment:this corresponds to a 83 (hex) in the upper byte of the PD;",
";",
"source:SI,SI,57,~CNTS,!median_of_vel._data_MHR_(horizontal);",
"; comment:this corresponds to a 93 (hex) in the upper byte of the PD;",
";",
"source:BS,BS,64,~CNTS,!primary_signal_to_noise_ratio_MHR_(horizontal);",
"; comment:this corresponds to a 04 (hex) in the upper byte of the PD;",
";",
"source:BF,BF,80,~CNTS,!primary_flags_field_MHR_(horizontal);",
"; comment:this corresponds to a 05 (hex) in the upper byte of the PD;",
";",
"source:BG,BG,81,~CNTS,!oct91_flags_field_MHR_(horizontal);",
"; comment:this corresponds to a 15 (hex) in the upper byte of the PD;",
";",
"source:BN,BN,96,~CNTS,!primary_NCP_field_MHR_(horizontal);",
"; comment:this corresponds to a 06 (hex) in the upper byte of the PD;",
";",
"source:PS,PS,65,~CNTS,!pre-clutter_filtered_SNR_(horizontal);",
"; comment:this corresponds to a 14 (hex) in the upper byte of the PD;",
";",
"source:PV,PV,66,~CNTS,!pre-clutter_filtered_vel._(horizontal);",
"; comment:this corresponds to a 24 (hex) in the upper byte of the PD;",
";",
"source:PW,PW,67,~CNTS,!pre-clutter_filtered_width_(horizontal);",
"; comment:this corresponds to a 34 (hex) in the upper byte of the PD;",
";",
"source:PZ,PZ,68,~CNTS,!pre-clutter_filtered_dBz_(horizontal);",
"; comment:this corresponds to a 44 (hex) in the upper byte of the PD;",
";",
"source:PN,PN,69,~CNTS,!pre-clutter_filtered_NCP_(horizontal);",
"; comment:this corresponds to a 54 (hex) in the upper byte of the PD;",
";",
"source:PC,PC,70,~CNTS,!pre-clutter_filtered_power_counts_(horizontal);",
"; comment:this corresponds to a 64 (hex) in the upper byte of the PD;",
";",
"quit;",
";",
";",
"comment:    the following set of attributes relate derived fields ",
"            and source fields;",
";",
"comment:    since the access package permits requesting radar parameters",
"            for derived fields this relationship must exist outside of",
"            GIVFLD;",
";",
";",
"dfield:WP,DM,~WATT,!primary_rec_pow_in_watts_(horizontal);",
";",
"dfield:DZ,DM,~DBZ.,!primary_dbz_thresholded_(horizontal);",
";",
"dfield:DZ,BZ,~DBZ.,!primary_dbz_MHR_thresholded_(horizontal);",
";",
"dfield:EZ,DM,~DBZ.,!primary_unthresholded_dbz_(horizontal);",
";",
"dfield:EZ,BZ,~DBZ.,!primary_unthresholded_dbz_MHR_(horizontal);",
";",
"dfield:FZ,BZ,~DBZ.,!primary_dbz_thresholded_RP7_(horizontal);",
";",
"dfield:NC,BN,~NCP.,!primary_normalized_coherent_power_(horizontal);",
";",
"dfield:NC,RT,~NCP.,!primary_normalized_coherent_power_(horizontal);",
";",
"dfield:NC,LX,~NCP.,!primary_normalized_coherent_power_(horizontal);",
";",
"dfield:NM,RT,~NCP.,!primary_NCP_numerator_(horizontal);",
";",
"dfield:NM,LX,~NCP.,!primary_NCP_numerator_(horizontal);",
";",
"dfield:NR,LM,~NCP.,!primary_NCP_denomenator_reciprocal_(horizontal);",
";",
"dfield:NR,LX,~NCP.,!primary_NCP_denomenator_reciprocal_(horizontal);",
";",
"dfield:VT,VR,~M/S.,!primary_thresholded_velocity_(horizontal);",
";",
"dfield:VT,VJ,~M/S.,!primary_thresholded_velocity_(horizontal);",
";",
"dfield:VE,VR,~M/S.,!primary_thresholded_velocity_(horizontal);",
";",
"dfield:VE,VJ,~M/S.,!primary_thresholded_velocity_(horizontal);",
";",
"dfield:VT,BV,~M/S.,!primary_thresholded_velocity_MHR_(horizontal);",
";",
"dfield:VE,BV,~M/S.,!primary_thresholded_velocity_MHR_(horizontal);",
";",
"dfield:VF,VR,~M/S.,!primary_unthresholded_velocity_(horizontal);",
";",
"dfield:VR,BV,~M/S.,!primary_unthresholded_velocity_(horizontal);",
";",
"dfield:VP,BV,~M/S.,!primary_velocity_thresholded_on_dbm_(horizontal);",
";",
"dfield:VP,VR,~M/S.,!primary_velocity_thresholded_on_dbm_(horizontal);",
";",
"dfield:XZ,XM,~DBZ.,!secondary_dbz_thresholded_(horizontal);",
";",
"dfield:GZ,BX,~DBZ.,!secondary_dbz_thresholded_MHR_(horizontal);",
";",
"dfield:XY,XL,~DBZ.,!secondary_dbz_thresholded_(vertical);",
";",
"dfield:SW,BW,~M/S.,!primary_spectral_width_MHR_(horizontal);",
";",
"dfield:SW,SR,~M/S.,!primary_spectral_width_(horizontal);",
";",
"dfield:SW,RT,~M/S.,!primary_spectral_width_(horizontal);",
";",
"dfield:SW,LX,~M/S.,!primary_spectral_width_(horizontal);",
";",
"dfield:FL,RT,~FLG.,!primary_flag_field_based_on_primary_coherent_power;",
";",
"dfield:FL,LX,~FLG.,!primary_flag_field_based_on_primary_coherent_power;",
";",
"dfield:FL,SR,~FLG.,!primary_flag_field_based_on_spectral_width;",
";",
"dfield:VS,VQ,~M/S.,!primary_unthresholded_velocity_(vertical);",
";",
"dfield:LD,XL,~LDDB,!secondary_linear_depolarization_ratio_(function_of_xl_&_xm);",
";",
"dfield:XU,XL,~LDDB,!secondary_unfolded_received_log_video_(vertical);",
";",
"dfield:KD,BL,~LDDB,!secondary_linear_depolarization_ratio_MHR;",
";",
"dfield:LZ,LM,~DBZ.,!primary_linear_dbz_unfolded_(horizontal);",
";",
"dfield:LU,LM,~DBM.,!primary_linear_dbm_unfolded_(horizontal);",
";",
"dfield:LZ,LX,~DBZ.,!primary_linear_dbz_(horizontal);",
";",
"dfield:LY,LL,~DBZ.,!primary_linear_dbz_(vertical);",
";",
"dfield:SM,DM,~SNDB,!primary_log_signal_to_noise_ratio_(horizontal);",
";",
"dfield:SN,BS,~SNDB,!primary_signal_to_noise_ratio_MHR_(horizontal);",
";",
"dfield:SN,BF,~SNDB,!primary_signal_to_noise_ratio_MHR_(horizontal);",
";",
"dfield:SN,BF,~SNDB,!primary_signal_to_noise_ratio_MHR_(horizontal);",
";",
"dfield:SN,LM,~SNDB,!primary_linear_signal_to_noise_ratio_(horizontal);",
";",
"dfield:SN,LX,~SNDB,!primary_signal_to_noise_ratio_(horizontal);",
";",
"dfield:ZD,ZR,~ZDDB,!primary_zdr_with_the_noise_removal_algorithm;",
";",
"dfield:ZD,BD,~ZDDB,!primary_zdr_with_the_noise_removal_algorithm_MHR;",
";",
"dfield:ZN,ZR,~ZDDB,!primary_zdr_with_the_noise_removal_algorithm;",
";",
"dfield:ZN,ZR,~ZDDB,!primary_zdr_with_the_noise_removal_algorithm;",
";",
"dfield:ZW,ZR,~ZDDB,!primary_reciprocal_of_ZR_in_watts;;",
";",
"dfield:DY,DL,~DBZ.,!primary_dbz_(vertical);",
";",
"dfield:DO,ZR,~DBM.,!primary_dbm_(vertical--function_of_dm_&_zr);",
";",
"dfield:VT,VJ,~M/S.,!primary_thresholded_velocity_(horizontal);",
";",
"; comment: funkiness to display counts;",
";",
"dfield:CP,DM,~CNTS,!primary_wavelength_received_log_video_(horizontal);",
";	     ",
"dfield:CD,ZR,~CNTS,!primary_polarization_diversity;",
";	     ",
"dfield:CN,DL,~CNTS,!primary_wavelength_received_log_video_(vertical);",
";	     ",
"dfield:CT,RT,~CNTS,!primary_r(tau)_(horizontal);",
";	     ",
"dfield:CO,LM,~CNTS,!primary_r(0)_(horizontal);",
";	     ",
"dfield:CX,XM,~CNTS,!secondary_wavelength_received_log_video_(horizontal);",
";	     ",
"dfield:CY,XL,~CNTS,!secondary_wavelength_received_log_video_(vertical);",
";	     ",
"dfield:CV,VR,~CNTS,!primary_wavelength_velocity_(horizontal);",
";	     ",
"dfield:CU,VQ,~CNTS,!primary_wavelength_velocity_(vertical);",
";	     ",
"dfield:CR,LW,~CNTS,!primary_compressed_r(0)_and_r(tau)_(vertical);",
";	     ",
"dfield:CQ,LX,~CNTS,!primary_compressed_r(0)_and_r(tau)_(horizontal);",
";	     ",
"dfield:CW,SR,~CNTS,!primary_spectral_width_data_(mist86+);",
";	     ",
"dfield:CM,RS,~CNTS,!primary_s/n_for_Lincoln_lab_tapes;",
";	     ",
"dfield:CL,LL,~CNTS,!primary_r(0)_(vertical);",
";",
";",
"quit;",
";",
"comment:  the units attribute associates the \"center\" and the \"increment\"",
"          for RDSS displays (assumes 17 steps);",
";",
"units:~CNTS,@127,#16;",
";",
"units:~DBM.,@-75,#5;",
";",
"units:~DBZ.,@25,#5;",
";",
"units:~M/S.,@0,#4;",
";",
"units:~SNDB,@30,#4;",
";",
"units:~ZDDB,@0,#2;",
";",
"units:~LDDB,@0,#2;",
";",
"units:~NCP.,@.5,#.1;",
";",
"units:~VFLG,@.5,#.1;",
";",
"units:~FLGS,@12.8,#1.6;",
";",
"quit;",
";",
";",
"comment:    define the relationship between the calibrated field, the radar,",
"    	    and the calibration title;",
";",
";",
"calibration:CP,?CP2,@:POWER_CALIBRATION_DATA_FOR_S-BAND;",
";",
"calibration:CO,?CP2,@:POWER_CALIBRATION_DATA_FOR_LINEAR_S-BAND;",
";",
"calibration:CX,?CP2,@:POWER_CALIBRATION_DATA_FOR_X-BAND;",
";",
"calibration:CY,?CP2,@:POWER_CALIBRATION_DATA_FOR_VERTICAL_X-BAND;",
";",
"calibration:CP,?CP3,@:POWER_CALIBRATION_DATA_FOR_C-BAND;",
";",
"calibration:CP,?CP4,@:POWER_CALIBRATION_DATA_FOR_C-BAND;",
";",
"calibration:CO,?CP4,@:POWER_CALIBRATION_DATA_FOR_LINEAR_C-BAND;",
";",
"quit;",
";",
}

static const char *fof_headerlist[] = {
";===========================================================;",
"PROJECT:  1995, SCMS;",
"PROJECT:  1994, RSFDEV94;",
"PROJECT:  1994, DRITEST;",
"PROJECT:  1994, WISP94;",
"PROJECT:  1993, TNEXRAD93;",
"PROJECT:  1993, CP4TEST;",
"PROJECT:  1993, RAPS93;",
"PROJECT:  1993, WISPIT, WISP93, WISPIT93;",
"PROJECT:  1993, TNEXRAD93;",
"PROJECT:  1992, RAPS92;",
"PROJECT:  1992, TNEXRAD92;",
"PROJECT:  1992, STORMFEST, FEST;",
"PROJECT:  1991, CAPE, CAPE91;",
"PROJECT:  1991, TNEXRAD91;",
"PROJECT:  1991, WISP91;",
"PROJECT:  1990, HARP, HARP90;",
"PROJECT:  1990, TNEXRAD90;",
"PROJECT:  1990, WISP90;",
"PROJECT:  1989, NDTP, NDTP89;",
"PROJECT:  1989, TNEXRAD89;",
"PROJECT:  1989, PROFS89;",
"PROJECT:  1988, TDWR88;",
"PROJECT:  1988, PROFS88;",
"PROJECT:  1987, TAMEX;",
"PROJECT:  1987, CINDE, TDWR, TDWR87, PROFS87;",
"PROJECT:  1986, MIST, SPACE, CP2TEST, COHMEX;",
"PROJECT:  1986, GALE, GALE86;",
"PROJECT:  1985, PRESTORM;",
"PROJECT:  1985, SIERRA85;",
"PROJECT:  1985, UTAH85;",
"PROJECT:  1984, SIERRA84;",
"PROJECT:  1984, SOCORRO84, SOCORO84;",
"PROJECT:  1984, MAYPOL84, PHOENIX, MAYPOLE84;",
"PROJECT:  1984, LAKESNOW;",
"PROJECT:  1983, LAKESNOW;",
"PROJECT:  1983, SOCORRO83, SOCORO83;",
"PROJECT:  1983, MAYPOL83,MAYPOLE83;",
"PROJECT:  1983, PROFS83;",
"PROJECT:  1982, SIERRA82;",
"PROJECT:  1982, CYCLES, CYCLES82;",
"PROJECT:  1982, JAWS, JAWS82;",
"PROJECT:  1981, CCOPE, COPE, HIPLEX;",
";===========================================================;",
"EXPERIMENT:DRITEST;   INSTRUMENT:ANON;  START:01-JAN-94,01:00;",
"                                        STOP:31-DEC-94,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:SCMS;      INSTRUMENT:CP2;  START:01-APR-95,01:00;",
"                                        STOP:22-JUL-95,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:SCMS;      INSTRUMENT:CP2;  START:23-JUL-95,01:00;",
"                                        STOP:31-DEC-95,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";===========================================================;",
"EXPERIMENT:RSFDEV94;  INSTRUMENT:CP2;  START:01-JAN-94,01:00;",
"                                        STOP:31-DEC-94,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:WISP94;    INSTRUMENT:CP4;  START:04-JAN-94,01:00;",
"                                        STOP:23-MAR-94,12:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:WISP94;    INSTRUMENT:CP4;  START:23-MAR-94,13:00;",
"                                        STOP:31-MAR-94,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";===========================================================;",
"EXPERIMENT:CP4TEST;   INSTRUMENT:CP4;  START:01-NOV-93,01:00;",
"                                        STOP:31-DEC-93,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:TNEXRAD94; INSTRUMENT:MHR;  START:01-JAN-93,00:01;",
"                                        STOP:31-DEC-93,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:RAPS93;    INSTRUMENT:CP2;  START:01-MAY-93,01:00;",
"                                        STOP:02-JUN-93,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS93;    INSTRUMENT:CP2;  START:03-JUN-93,00:00;",
"                                        STOP:04-JUN-93,18:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS93;    INSTRUMENT:CP2;  START:04-JUN-93,19:00;",
"                                        STOP:08-JUN-93,23:00;",
"                                      HEADER:HEADERC;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS93;    INSTRUMENT:CP2;  START:09-JUN-93,01:00;",
"                                        STOP:10-JUN-93,12:00;",
"                                      HEADER:HEADERD;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS93;    INSTRUMENT:CP2;  START:10-JUN-93,13:00;",
"                                        STOP:02-JUL-93,12:00;",
"                                      HEADER:HEADERE;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS93;    INSTRUMENT:CP2;  START:02-JUL-93,13:00;",
"                                        STOP:07-JUL-93,12:00;",
"                                      HEADER:HEADERF;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS93;    INSTRUMENT:CP2;  START:07-JUL-93,13:00;",
"                                        STOP:18-JUL-93,23:00;",
"                                      HEADER:HEADERG;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS93;    INSTRUMENT:CP2;  START:19-JUL-93,00:00;",
"                                        STOP:31-DEC-93,23:00;",
"                                      HEADER:HEADERH;   QUIT;",
";===========================================================;",
"EXPERIMENT:WISPIT;    INSTRUMENT:CP2;  START:16-JAN-93,01:00;",
"                                        STOP:17-FEB-93,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:WISPIT;    INSTRUMENT:CP2;  START:18-FEB-93,01:00;",
"                                        STOP:21-FEB-93,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:WISPIT;    INSTRUMENT:CP2;  START:22-FEB-93,01:00;",
"                                        STOP:30-APR-93,23:00;",
"                                      HEADER:HEADERC;   QUIT;",
";===========================================================;",
"EXPERIMENT:TNEXRAD93; INSTRUMENT:MHR;  START:01-JAN-93,00:01;",
"                                        STOP:31-DEC-93,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:RAPS92;    INSTRUMENT:CP2;  START:01-MAY-92,01:00;",
"                                        STOP:17-JUN-92,16:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS92;    INSTRUMENT:CP2;  START:17-JUN-92,17:00;",
"                                        STOP:14-JUL-92,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS92;    INSTRUMENT:CP2;  START:15-JUL-92,01:00;",
"                                        STOP:23-AUG-92,23:00;",
"                                      HEADER:HEADERC;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS92;    INSTRUMENT:CP2;  START:24-AUG-92,01:00;",
"                                        STOP:28-AUG-92,23:00;",
"                                      HEADER:HEADERD;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS92;    INSTRUMENT:CP2;  START:29-AUG-92,01:00;",
"                                        STOP:30-SEP-92,23:00;",
"                                      HEADER:HEADERE;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:RAPS92;    INSTRUMENT:CP2;  START:01-OCT-92,01:00;",
"                                        STOP:15-JAN-93,23:00;",
"                                      HEADER:HEADERF;   QUIT;",
";===========================================================;",
"EXPERIMENT:TNEXRAD92; INSTRUMENT:MHR;  START:01-JAN-92,01:00;  ",
"                                        STOP:31-DEC-92,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:STORMFEST;INSTRUMENT:CP3;   START:04-JAN-92,01:00;",
"                                        STOP:04-MAR-92,22:10;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:STORMFEST;INSTRUMENT:CP3;   START:04-MAR-92,22:11;",
"                                        STOP:30-MAR-92,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:STORMFEST;INSTRUMENT:CP4;   START:04-JAN-92,01:00;",
"                                        STOP:29-FEB-92,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:STORMFEST;INSTRUMENT:CP4;   START:01-MAR-92,01:00;",
"                                        STOP:05-MAR-92,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:STORMFEST;INSTRUMENT:CP4;   START:06-MAR-92,01:00;",
"                                        STOP:10-MAR-92,23:00;",
"                                      HEADER:HEADERC;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:STORMFEST;INSTRUMENT:CP4;   START:11-MAR-92,01:00;",
"                                        STOP:13-MAR-92,19:00;",
"                                      HEADER:HEADERD;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:STORMFEST;INSTRUMENT:CP4;   START:13-MAR-92,20:00;",
"                                        STOP:30-MAR-92,23:00;",
"                                      HEADER:HEADERE;   QUIT;",
";===========================================================;",
"EXPERIMENT:CAPE;    INSTRUMENT:CP2;    START:01-MAY-91,01:00;",
"                                        STOP:30-SEP-91,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:CAPE;    INSTRUMENT:CP3;    START:01-MAY-91,01:00;",
"                                        STOP:18-JUL-91,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:CAPE;    INSTRUMENT:CP3;    START:19-JUL-91,01:00;",
"                                        STOP:30-SEP-91,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:CAPE;    INSTRUMENT:CP4;    START:01-MAY-91,01:00;",
"                                        STOP:30-SEP-91,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:TNEXRAD91; INSTRUMENT:MHR;  START:01-JAN-91,01:00;  ",
"                                        STOP:31-DEC-91,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP2;    START:03-JAN-91,01:00;",
"                                        STOP:23-FEB-91,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP2;    START:24-FEB-91,01:00;",
"                                        STOP:31-MAR-91,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP4;    START:03-JAN-91,01:00;",
"                                        STOP:04-FEB-91,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP4;    START:05-FEB-91,01:00;",
"                                        STOP:07-FEB-91,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP4;    START:08-FEB-91,01:00;",
"                                        STOP:15-FEB-91,23:00;",
"                                      HEADER:HEADERC;   QUIT;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP4;    START:16-FEB-91,01:00;",
"                                        STOP:18-FEB-91,23:00;",
"                                      HEADER:HEADERD;   QUIT;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP4;    START:19-FEB-91,01:00;",
"                                        STOP:25-FEB-91,23:00;",
"                                      HEADER:HEADERE;   QUIT;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP4;    START:26-FEB-91,01:00;",
"                                        STOP:02-MAR-91,23:00;",
"                                      HEADER:HEADERF;   QUIT;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP4;    START:03-MAR-91,01:00;",
"                                        STOP:06-MAR-91,23:00;",
"                                      HEADER:HEADERG;   QUIT;",
"EXPERIMENT:WISP91;  INSTRUMENT:CP4;    START:07-MAR-91,01:00;",
"                                        STOP:30-APR-91,23:00;",
"                                      HEADER:HEADERH;   QUIT;",
";===========================================================;",
"EXPERIMENT:HARP;  INSTRUMENT:CP3;      START:01-MAY-90,01:00;",
"                                        STOP:15-SEP-90,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:HARP;  INSTRUMENT:CP4;      START:01-MAY-90,01:00;",
"                                        STOP:15-SEP-90,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:TNEXRAD90; INSTRUMENT:MHR;  START:01-JAN-90,01:00;",
"                                        STOP:30-MAY-90,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:TNEXRAD90; INSTRUMENT:MHR;  START:31-MAY-90,01:00;  ",
"                                        STOP:31-DEC-90,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";===========================================================;",
"EXPERIMENT:WISP90;  INSTRUMENT:CP3;    START:05-JAN-90,01:00;",
"                                        STOP:30-APR-90,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:NDTP;  INSTRUMENT:CP3;      START:06-JUN-89,01:00;",
"                                        STOP:28-JUN-89,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:NDTP;  INSTRUMENT:CP3;      START:29-JUN-89,01:00;",
"                                        STOP:31-JUL-89,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:NDTP;  INSTRUMENT:CP4;      START:06-JUN-89,01:00;",
"                                        STOP:24-JUN-89,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:NDTP;  INSTRUMENT:CP4;      START:25-JUN-89,01:00;",
"                                        STOP:30-JUN-89,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
"EXPERIMENT:NDTP;  INSTRUMENT:CP4;      START:01-JUL-89,01:00;",
"                                        STOP:31-JUL-89,23:00;",
"                                      HEADER:HEADERC;   QUIT;",
";===========================================================;",
"EXPERIMENT:TNEXRAD89; INSTRUMENT:MHR;  START:01-MAY-89,01:00;  ",
"                                    STOP:31-DEC-89,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:PROFS89; INSTRUMENT:CP2;  START:01-JAN-89,01:00;  ",
"                                    STOP:01-AUG-89,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:TDWR88; INSTRUMENT:LLAB;  START:01-MAY-88,01:00;  ",
"                                    STOP:30-SEP-88,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:PROFS88; INSTRUMENT:CP2;  START:01-JAN-88,01:00;  ",
"                                    STOP:30-APR-88,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";",
"EXPERIMENT:PROFS88; INSTRUMENT:CP2;  START:01-MAY-88,01:00;  ",
"                                    STOP:31-DEC-88,23:00;",
"                                  HEADER:HEADERB;   QUIT;",
";===========================================================;",
"EXPERIMENT:TAMEX; INSTRUMENT:CP4;  START:04-MAY-87,01:00;",
"                                    STOP:26-JUN-87,23:55;",
"                                  HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:CINDE; INSTRUMENT:CP2;  START:15-FEB-87,01:00;  ",
"                                    STOP:26-MAR-87,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP2;  START:27-MAR-87,01:00;  ",
"                                    STOP:14-APR-87,23:00;",
"                                  HEADER:HEADERB;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP2;  START:15-APR-87,01:00;  ",
"                                    STOP:01-JUL-87,23:00;",
"                                  HEADER:HEADERC;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP2;  START:02-JUL-87,01:00;  ",
"                                    STOP:10-JUL-87,23:00;",
"                                  HEADER:HEADERD;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP2;  START:11-JUL-87,01:00;  ",
"                                    STOP:14-JUL-87,23:00;",
"                                  HEADER:HEADERE;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP2;  START:15-JUL-87,01:00;  ",
"                                    STOP:31-AUG-87,23:00;",
"                                  HEADER:HEADERF;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP2;  START:01-SEP-87,01:00;  ",
"                                    STOP:31-DEC-87,23:00;",
"                                  HEADER:HEADERG;   QUIT;",
";----------------------------------------------------------;",
"EXPERIMENT:CINDE; INSTRUMENT:CP3;  START:22-JUN-87,01:00;  ",
"                                    STOP:14-JUL-87,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP3;  START:15-JUL-87,01:00;",
"                                    STOP:15-JUL-87,23:00;",
"                                  HEADER:HEADERB;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP3;  START:16-JUL-87,01:00;",
"                                    STOP:16-JUL-87,23:00;",
"                                  HEADER:HEADERC;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP3;  START:17-JUL-87,01:00;  ",
"                                    STOP:17-JUL-87,23:00;",
"                                  HEADER:HEADERD;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP3;  START:18-JUL-87,01:00;",
"                                    STOP:18-JUL-87,23:00;",
"                                  HEADER:HEADERE;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP3;  START:19-JUL-87,01:00;",
"                                    STOP:19-JUL-87,23:00;",
"                                  HEADER:HEADERF;   QUIT;",
";",
"EXPERIMENT:CINDE; INSTRUMENT:CP3;  START:20-JUL-87,01:00;  ",
"                                    STOP:05-SEP-87,23:00;",
"                                  HEADER:HEADERG;   QUIT;",
";===========================================================;",
"EXPERIMENT:MIST; INSTRUMENT:CP2;   START:19-MAY-86,19:48;",
"                                    STOP:27-JUN-86,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";",
"EXPERIMENT:MIST;  INSTRUMENT:CP2;  START:28-JUN-86,01:00;  ",
"                                    STOP:31-JUL-86,23:00;",
"                                  HEADER:HEADERB;   QUIT;",
";",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:MIST;  INSTRUMENT:CP3;  START:15-MAY-86,01:00;  ",
"                                    STOP:11-JUN-86,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";",
"EXPERIMENT:MIST;  INSTRUMENT:CP3;  START:11-JUN-86,23:30; ",
"                                    STOP:27-JUN-86,23:00;",
"                                  HEADER:HEADERB;   QUIT;",
";",
"EXPERIMENT:MIST;  INSTRUMENT:CP3;  START:28-JUN-86,01:00; ",
"                                    STOP:11-JUL-86,23:00;",
"                                  HEADER:HEADERC;   QUIT;",
";",
"EXPERIMENT:MIST;  INSTRUMENT:CP3;  START:12-JUL-86,01:00; ",
"                                    STOP:28-JUL-86,23:00;",
"                                  HEADER:HEADERD;   QUIT;",
";",
"EXPERIMENT:MIST;  INSTRUMENT:CP3;  START:29-JUL-86,01:00; ",
"                                    STOP:31-JUL-86,23:00;",
"                                  HEADER:HEADERE;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:MIST;  INSTRUMENT:CP4;  START:15-MAY-86,01:00; ",
"                                    STOP:31-JUL-86,23:00;",
"                                  HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:GALE;  INSTRUMENT:CP3;       START:8-JAN-86,08:00;",
"                                        STOP:29-JAN-86,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:GALE;  INSTRUMENT:CP3;      START:29-JAN-86,23:30;",
"                                        STOP:15-MAR-86,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:GALE;  INSTRUMENT:CP4;      START:8-JAN-86,08:00;",
"                                       STOP:29-JAN-86,23:30;",
"                                      HEADER:HEADERA;  QUIT;",
";",
"EXPERIMENT:GALE;  INSTRUMENT:CP4;      START:29-JAN-86,23:30;",
"                                        STOP:07-FEB-86,16:00;",
"                                      HEADER:HEADERB;   QUIT;",
";",
"EXPERIMENT:GALE;  INSTRUMENT:CP4;      START:07-FEB-86,16:30;",
"                                        STOP:10-FEB-86,07:00;",
"                                      HEADER:HEADERC;   QUIT;",
";",
"EXPERIMENT:GALE;  INSTRUMENT:CP4;      START:10-FEB-86,07:30;",
"                                        STOP:27-FEB-86,07:00;",
"                                      HEADER:HEADERD;   QUIT;",
";",
"EXPERIMENT:GALE;  INSTRUMENT:CP4;      START:27-FEB-86,08:30;",
"                                        STOP:15-MAR-86,23:00;",
"                                      HEADER:HEADERE;   QUIT;",
";===========================================================;",
"EXPERIMENT:PRESTORM;  INSTRUMENT:CP3;  START:1-MAY-85,08:00;",
"                                        STOP:16-MAY-85,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";",
"EXPERIMENT:PRESTORM;  INSTRUMENT:CP3;  START:17-MAY-85,01:00;",
"                                        STOP:30-JUN-85,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:PRESTORM;  INSTRUMENT:CP4;  START:1-MAY-85,08:00;",
"                                        STOP:2-JUN-85,23:30;",
"                                      HEADER:HEADERA;  QUIT;",
";",
"EXPERIMENT:PRESTORM;  INSTRUMENT:CP4;  START:3-JUN-85,01:00;",
"                                        STOP:10-JUN-85,05:00;",
"                                      HEADER:HEADERB;   QUIT;",
";",
"EXPERIMENT:PRESTORM;  INSTRUMENT:CP4;  START:10-JUN-85,05:30;",
"                                        STOP:30-JUN-85,23:30;",
"                                      HEADER:HEADERC;   QUIT;",
";===========================================================;",
"EXPERIMENT:SIERRA85;  INSTRUMENT:CP4;  START:25-FEB-85,01:00;  ",
"                                        STOP:31-MAR-85,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:UTAH85;    INSTRUMENT:CP3;  START:15-JAN-85,01:00;  ",
"                                        STOP:10-MAR-85,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";",
"EXPERIMENT:UTAH85;    INSTRUMENT:CP3;  START:11-MAR-85,01:00;  ",
"                                        STOP:16-MAR-85,23:00;",
"                                      HEADER:HEADERB;   QUIT;",
";===========================================================;",
"EXPERIMENT:SIERRA84;  INSTRUMENT:CP4;  START:14-FEB-84,01:00;  ",
"                                        STOP:31-MAR-84,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:MAYPOL84;  INSTRUMENT:CP2;  START:15-MAY-84,12:00;  ",
"                                        STOP:30-JUN-84,23:00; ",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:MAYPOL84; INSTRUMENT:CP3;   START:15-JUN-84,10:20;",
"                                        STOP:29-JUN-84,16:00;",
"                                      HEADER:HEADERA;   QUIT;",
";-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - ;",
"EXPERIMENT:MAYPOL84;  INSTRUMENT:CP4;  START:15-MAY-84,08:00;  ",
"                                        STOP:30-JUN-84,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
" ",
";===========================================================;",
" EXPERIMENT:SOCORRO84; INSTRUMENT:CP4; START:14-JUL-84,10:19;",
"                                        STOP:04-AUG-84,24:00;",
"                                      HEADER:HEADERA;   QUIT;",
" EXPERIMENT:SOCORRO84; INSTRUMENT:CP4; START:06-AUG-84,10:00;",
"                                        STOP:24-AUG-84,12:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
" EXPERIMENT:SOCORRO84; INSTRUMENT:CP3; START:07-JUL-84,09:40;",
"                                        STOP:07-AUG-84,24:00;",
"                                      HEADER:HEADERA;   QUIT;",
" EXPERIMENT:SOCORRO84; INSTRUMENT:CP3; START:12-AUG-84,10:59;",
"                                        STOP:23-AUG-84,13:30;",
"                                      HEADER:HEADERB;   QUIT;",
";===========================================================;",
"EXPERIMENT:LAKESNOW;  INSTRUMENT:CP4;  START:02-DEC-83,05:37;",
"                                        STOP:12-DEC-83,24:00;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:LAKESNOW;  INSTRUMENT:CP4;  START:13-DEC-83,08:20;",
"                                        STOP:31-JAN-84,24:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:LAKESNOW; INSTRUMENT:CP3;   START:01-DEC-83,07:00;",
"                                        STOP:03-DEC-83,20:00;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:LAKESNOW; INSTRUMENT:CP3;   START:06-DEC-83,07:52;",
"                                        STOP:29-DEC-83,15:00;",
"                                      HEADER:HEADERB;   QUIT;",
"EXPERIMENT:LAKESNOW; INSTRUMENT:CP3;   START:30-DEC-83,08:30;",
"                                        STOP:14-JAN-84,11:35;",
"                                      HEADER:HEADERC;   QUIT;",
"EXPERIMENT:LAKESNOW; INSTRUMENT:CP3;   START:15-JAN-84,06:15;",
"                                        STOP:26-JAN-84,11:45;",
"                                      HEADER:HEADERD;   QUIT;",
";===========================================================;",
"EXPERIMENT:SOCORRO83; INSTRUMENT:CP3;  START:29-JUN-83,12:00;",
"                                        STOP:17-AUG-83,13:30;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:MAYPOL83;  INSTRUMENT:CP2;  START:01-MAY-83,00:01;",
"                                        STOP:15-JUN-83,23:55;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:PROFS83;   INSTRUMENT:CP2;  START:16-JUN-83,00:01;",
"                                        STOP:15-SEP-83,23:55;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:CYCLES;    INSTRUMENT:CP3;  START:01-JAN-82,01:00;  ",
"                                        STOP:16-FEB-82,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
"; - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ;",
"EXPERIMENT:CYCLES;    INSTRUMENT:CP4;  START:01-JAN-82,01:00;  ",
"                                        STOP:16-FEB-82,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:JAWS;      INSTRUMENT:CP2;  START:15-APR-82,06:00;",
"                                        STOP:22-AUG-82,24:00;",
"                                       HEADER:HEADERA;  QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:JAWS;      INSTRUMENT:CP3;  START:11-MAY-82,09:00;",
"                                        STOP:16-JUL-82,20:00;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:JAWS;      INSTRUMENT:CP3;  START:17-JUL-82,06:00;",
"                                        STOP:13-AUG-82,16:00;",
"                                      HEADER:HEADERB;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:JAWS;      INSTRUMENT:CP4;  START:22-MAY-82,16:40;",
"                                        STOP:21-JUL-82,17:30;",
"                                      HEADER:HEADERA;   QUIT;",
"EXPERIMENT:JAWS;      INSTRUMENT:CP4;  START:26-JUL-82,14:55;",
"                                        STOP:08-AUG-82,16:30;",
"                                      HEADER:HEADERB;   QUIT;",
"EXPERIMENT:JAWS;      INSTRUMENT:CP4;  START:09-AUG-82,16:00;",
"                                        STOP:13-AUG-82,15:02;",
"                                      HEADER:HEADERC;   QUIT;",
";===========================================================;",
"EXPERIMENT:SIERRA82;  INSTRUMENT:CP3;  START:01-MAR-82,00:01;",
"                                        STOP:01-APR-82,23:55;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
"EXPERIMENT:CCOPE;     INSTRUMENT:CP2   START:21-MAY-81,00:01;",
"                                        STOP:07-AUG-81,23:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:CCOPE;     INSTRUMENT:CP3;  START:20-MAY-81,14:00;",
"                                        STOP:07-AUG-81,19:00;",
"                                      HEADER:HEADERA;   QUIT;",
";- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -;",
"EXPERIMENT:CCOPE;     INSTRUMENT:CP4;  START:14-MAY-81,11:50;",
"                                        STOP:06-AUG-81,20:00;",
"                                      HEADER:HEADERA;   QUIT;",
";===========================================================;",
";",
}


# endif
#endif
